# Generated by Django 4.2.16 on 2025-05-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код ступени')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Возрастная ступень',
                'verbose_name_plural': 'Возрастные ступени',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код навыка')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('distance', models.FloatField(verbose_name='Протяженность (км)')),
                ('duration', models.FloatField(verbose_name='Продолжительность (в часах)')),
                ('transportation_method', models.CharField(choices=[('пеший', 'Пеший'), ('велосипедный', 'Велосипедный'), ('лыжный', 'Лыжный'), ('водный', 'Водный')], max_length=50, verbose_name='Способ передвижения')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость (руб)')),
                ('event_dates', models.TextField(blank=True, null=True, verbose_name='Даты проведения')),
                ('organizer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО организатора')),
                ('organizer_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('organizer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('organization', models.TextField(blank=True, null=True, verbose_name='Организация')),
                ('route_passport', models.URLField(blank=True, null=True, verbose_name='Паспорт маршрута')),
                ('image', models.ImageField(blank=True, null=True, upload_to='routes_images', verbose_name='Изображение')),
                ('map_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на карту')),
                ('age_groups', models.ManyToManyField(to='main.agegroup', verbose_name='Возрастные ступени')),
                ('seasons', models.ManyToManyField(to='main.season', verbose_name='Сезоны доступности')),
                ('skills', models.ManyToManyField(to='main.skill', verbose_name='Проверяемые навыки')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ('id',),
            },
        ),
    ]
