# Generated by Django 4.2.16 on 2025-01-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='Уровень')),
                ('duration', models.FloatField(verbose_name='Продолжительность')),
                ('distance', models.FloatField(verbose_name='Протяженность в км')),
                ('transportation_method', models.CharField(max_length=50, verbose_name='Способ передвижения')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('event_date', models.DateField(verbose_name='Дата проведения')),
                ('organizing_agency', models.TextField(blank=True, null=True, verbose_name='Проводящая организация')),
                ('contact_info', models.TextField(verbose_name='Контактные данные')),
                ('skill_name', models.TextField(verbose_name='Название навыка')),
                ('map_link', models.URLField(verbose_name='Ссылка на карту маршрута')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_images', verbose_name='Изображение маршрута')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'db_table': 'route',
                'ordering': ('id',),
            },
        ),
    ]
