# Generated by Django 4.2.16 on 2025-06-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroup',
            name='max_age',
            field=models.PositiveIntegerField(default=59, verbose_name='Максимальный возраст'),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='min_age',
            field=models.PositiveIntegerField(default=11, verbose_name='Минимальный возраст'),
        ),
    ]
