# Generated by Django 4.2.16 on 2025-06-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_agegroup_max_age_agegroup_min_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_description',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Полное описание навыка'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(blank=True, max_length=500, unique=True, verbose_name='Название навыка'),
        ),
    ]
